name: run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upgrade pip, setuptools, and wheel
        run: pip install --upgrade pip setuptools wheel


      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install surprise
        run: |
          pip install --use-pep517 surprise

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai streamlit
          pip install firebase-admin
      
      - name: test with pytest
        run: |
          pip install pytest
          pytest