name: Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pytest lightgbm scikit-learn firebase-admin openai streamlit tensorflow category_encoders

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/chatbots" >> $GITHUB_ENV
      

      - name: Test with pytest
        run: |
            pytest chatbot
