name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install Dependencies
        run: pip install -r chatbot/requirements.txt

      - name: Lint with Flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Uncomment and use this to test with Pytest, if you need it
      #- name: Test with Pytest
      #  run: |
      #    pip install pytest
      #    pytest chatbot/tests

      # If you want to deploy or run the streamlit app
      - name: Run Streamlit App
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # If you have Firebase credentials secret, uncomment the next line
          # FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          # If you have Firebase credentials JSON, uncomment and create a file from the secret
          # echo "$FIREBASE_CREDENTIALS" > ./chatbot/credentials.json
          streamlit run chatbot/app2.py
