name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install Dependencies
      run: pip install -r chatbot/requirements.txt

    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with Pytest
      run: |
        pip install pytest
        pytest 

    - name: Use Secret
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Using secret in script"
        python chatbot/firebase_chatbot.py

    - name: Create JSON file from secret
      run: |
        echo '${{ secrets.CREDENTIALS }}' > chatbot/credentials.json
      shell: bash
    
    - name: Print OpenAI API Key
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "OpenAI API Key: $OPENAI_API_KEY"
      
        