name: CI_CD

# Defines the event for which the action will run
on:
  push:
    branches:
      - main

# Defines the jobs to be run
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      # Run the Python script
      - name: Execute Python script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          export OPENAI_API_KEY=$OPENAI_API_KEY
          python chatbot_comment.py "Your input string for previous_answer"